# Generated by Django 4.1.2 on 2022-11-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_receta', models.CharField(max_length=50)),
                ('ingrediente_1', models.CharField(max_length=50)),
                ('cantidad_ingr_1', models.IntegerField()),
                ('ingrediente_2', models.CharField(max_length=50)),
                ('cantidad_ingr_2', models.IntegerField()),
                ('ingrediente_3', models.CharField(max_length=50)),
                ('cantidad_ingr_3', models.IntegerField()),
            ],
        ),
    ]
