# Generated by Django 4.1.2 on 2022-11-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_recetas', '0003_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(max_length=50)),
                ('paso_a_paso', models.CharField(default='Descripcion del ejercicio', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
