# Generated by Django 4.1.2 on 2022-11-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_recetas', '0004_ejercicio_delete_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(default='masculino', max_length=50),
            preserve_default=False,
        ),
    ]
