# Generated by Django 4.1.3 on 2022-11-29 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_recetas', '0007_alter_ejercicio_nombre_ejercicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='ciudad',
            new_name='dni',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='pais',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='provincia',
        ),
    ]
